[package]
name = "rna_pred_rust"
version = "0.0.1"
edition = "2021"

[[bin]]
name = "rna_pred_rust"
path = "src/main.rs"

[dependencies]
#arrayvec = {version = "0.7.4", features = ["serde"]}
#blas-src = { version = "0.9", features = ["openblas"]}
#blas-sys = { version = "*",  default-features=false, features=["openblas"] }
csv = "1.3.0"
itertools = "0.12.1"
logsumexp = "0.1.0" #Compare with the logaddexp crate
nalgebra = "0.32.5"
#nalgebra = { version = "0.32.5", features = ["rand"] }
#ndarray = "0.15.6" #features=["blas"]
num_enum = "0.7.2"
rayon = "1.10.0"
serde = { version = "1.0.199", features = ["derive"] }

[profile.release]
lto = true
