[package]
name = "rna_pred_rust"
version = "0.0.1"

[[bin]]
name = "rna_pred_rust"
path = "src/main.rs"

[dependencies]
expm = "0.1.1"
logsumexp = "0.1.0"
nalgebra = "0.32.5"
# Very old version, the one expm uses
ndarray = "0.12"
#ndarray = "0.15.6"
num_enum = "0.7.2"
rand = "0.8.5"
tree_iterators_rs = "1.2.1"
