name: fs_torch
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - amply=0.1.6=pyhd8ed1ab_0
  - annotated-types=0.7.0=pyhd8ed1ab_0
  - appdirs=1.4.4=pyh9f0ad1d_0
  - argparse-dataclass=2.0.0=pyhd8ed1ab_0
  - attrs=24.2.0=pyh71513ae_0
  - biopython=1.84=py312h9a8786e_0
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - cffi=1.17.1=py312h06ac9bb_0
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - coin-or-cbc=2.10.12=h8b142ea_1
  - coin-or-cgl=0.60.9=h1d3f3f2_0
  - coin-or-clp=1.17.10=h07f2a63_0
  - coin-or-osi=0.108.11=h6514dde_1
  - coin-or-utils=2.11.12=h99da652_1
  - coincbc=2.10.12=1_metapackage
  - colorama=0.4.6=pyhd8ed1ab_0
  - coloredlogs=15.0.1=pyhd8ed1ab_3
  - conda-inject=1.3.2=pyhd8ed1ab_0
  - configargparse=1.7=pyhd8ed1ab_0
  - connection_pool=0.0.3=pyhd3deb0d_0
  - cpython=3.12.7=py312hd8ed1ab_0
  - cuda-cudart=12.6.77=h5888daf_0
  - cuda-cudart_linux-64=12.6.77=h3f2d84a_0
  - cuda-nvrtc=12.6.77=hbd13f7d_0
  - cuda-nvtx=12.6.77=hbd13f7d_0
  - cuda-version=12.6=h7480c83_3
  - cudnn=9.3.0.75=h93bb076_0
  - datrie=0.8.2=py312h66e93f0_8
  - docutils=0.21.2=pyhd8ed1ab_0
  - dpath=2.2.0=pyha770c72_0
  - eido=0.2.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - filelock=3.16.1=pyhd8ed1ab_0
  - fsspec=2024.9.0=pyhff2d567_0
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.43=pyhd8ed1ab_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.1.5=py312h7201bc8_2
  - h2=4.1.0=pyhd8ed1ab_0
  - hmmer=3.4=hdbdd923_2
  - hpack=4.0.0=pyh9f0ad1d_0
  - humanfriendly=10.0=pyhd8ed1ab_6
  - hyperframe=6.0.1=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_0
  - immutables=0.21=py312h66e93f0_0
  - importlib_resources=6.4.5=pyhd8ed1ab_0
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jinja2=3.1.4=pyhd8ed1ab_0
  - jsonschema=4.23.0=pyhd8ed1ab_0
  - jsonschema-specifications=2024.10.1=pyhd8ed1ab_0
  - jupyter_core=5.7.2=pyh31011fe_1
  - ld_impl_linux-64=2.43=h712a8e2_1
  - libabseil=20240722.0=cxx17_h5888daf_1
  - libblas=3.9.0=24_linux64_openblas
  - libcblas=3.9.0=24_linux64_openblas
  - libcublas=12.6.3.3=hbd13f7d_0
  - libcufft=11.3.0.4=hbd13f7d_0
  - libcurand=10.3.7.77=hbd13f7d_0
  - libcusolver=11.7.1.2=hbd13f7d_0
  - libcusparse=12.5.4.2=hbd13f7d_0
  - libexpat=2.6.3=h5888daf_0
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran-ng=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - libhwloc=2.11.1=default_hecaa2ac_1000
  - libiconv=1.17=hd590300_2
  - liblapack=3.9.0=24_linux64_openblas
  - liblapacke=3.9.0=24_linux64_openblas
  - libmagma=2.8.0=h0af6554_0
  - libmagma_sparse=2.8.0=h0af6554_0
  - libnsl=2.0.1=hd590300_0
  - libnvjitlink=12.6.77=hbd13f7d_1
  - libopenblas=0.3.27=pthreads_hac2b453_1
  - libprotobuf=5.27.5=h5b01275_2
  - libsqlite=3.46.1=hadc24fc_0
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libstdcxx-ng=14.2.0=h4852527_1
  - libtorch=2.4.1=cuda120_h1d34654_301
  - libuuid=2.38.1=h0b41bf4_0
  - libuv=1.49.1=hb9d3cd8_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.12.7=he7c6b58_4
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=19.1.1=h024ca30_1
  - logmuse=0.2.8=pyhd8ed1ab_0
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.1=py312h178313f_1
  - maturin=1.7.4=py312h6ab59e4_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2023.2.0=h84fe81f_50496
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpmath=1.3.0=pyhd8ed1ab_0
  - nbformat=5.10.4=pyhd8ed1ab_0
  - nccl=2.23.4.1=h52f6c39_0
  - ncurses=6.5=he02047a_1
  - networkx=3.4.1=pyhd8ed1ab_0
  - numpy=2.1.2=py312h58c1407_0
  - openssl=3.3.2=hb9d3cd8_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.3=py312hf9745cd_1
  - patchelf=0.17.2=h58526e2_0
  - pephubclient=0.4.4=pyhd8ed1ab_0
  - peppy=0.40.7=pyhd8ed1ab_1
  - pip=24.2=pyh8b19718_1
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_1
  - plac=1.4.3=pyhd8ed1ab_0
  - platformdirs=4.3.6=pyhd8ed1ab_0
  - pluggy=1.5.0=pyhd8ed1ab_0
  - psutil=6.0.0=py312h66e93f0_2
  - pulp=2.8.0=py312h7900ff3_0
  - pycparser=2.22=pyhd8ed1ab_0
  - pydantic=2.9.2=pyhd8ed1ab_0
  - pydantic-core=2.23.4=py312h12e396e_0
  - pygments=2.18.0=pyhd8ed1ab_0
  - pyparsing=3.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.3.3=pyhd8ed1ab_0
  - python=3.12.7=hc5c86c4_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-fastjsonschema=2.20.0=pyhd8ed1ab_0
  - python-tzdata=2024.2=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.1=cuda120_py312hf8d5e09_301
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h66e93f0_1
  - readline=8.2=h8228510_1
  - referencing=0.35.1=pyhd8ed1ab_0
  - requests=2.32.3=pyhd8ed1ab_0
  - reretry=0.11.8=pyhd8ed1ab_0
  - rich=13.9.2=pyhd8ed1ab_0
  - rpds-py=0.20.0=py312h12e396e_1
  - setuptools=75.1.0=pyhd8ed1ab_0
  - shellingham=1.5.4=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - slack-sdk=3.33.1=pyha770c72_0
  - slack_sdk=3.33.1=hd8ed1ab_0
  - sleef=3.7=h1b44611_0
  - smart_open=7.0.5=pyhd8ed1ab_1
  - smmap=5.0.0=pyhd8ed1ab_0
  - snakemake=8.24.0=hdfd78af_0
  - snakemake-interface-common=1.17.4=pyhdfd78af_0
  - snakemake-interface-executor-plugins=9.3.2=pyhdfd78af_0
  - snakemake-interface-report-plugins=1.1.0=pyhdfd78af_0
  - snakemake-interface-storage-plugins=3.3.0=pyhdfd78af_0
  - snakemake-minimal=8.24.0=pyhdfd78af_0
  - sympy=1.13.3=pyh2585a3b_104
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.13.0=h84d6215_0
  - throttler=1.2.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tomli=2.0.2=pyhd8ed1ab_0
  - traitlets=5.14.3=pyhd8ed1ab_0
  - typer=0.12.5=pyhd8ed1ab_0
  - typer-slim=0.12.5=pyhd8ed1ab_0
  - typer-slim-standard=0.12.5=hd8ed1ab_0
  - typing-extensions=4.12.2=hd8ed1ab_0
  - typing_extensions=4.12.2=pyha770c72_0
  - tzdata=2024b=hc8b5060_0
  - ubiquerg=0.8.0=pyhd8ed1ab_0
  - urllib3=2.2.3=pyhd8ed1ab_0
  - veracitools=0.1.3=py_0
  - wheel=0.44.0=pyhd8ed1ab_0
  - wrapt=1.16.0=py312h66e93f0_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yte=1.5.4=pyha770c72_0
  - zipp=3.20.2=pyhd8ed1ab_0
  - zstandard=0.23.0=py312hef9b889_1
  - zstd=1.5.6=ha6fb4c9_0
  - pip:
      - felsenstein-rs==0.1.0
prefix: /home/benjamin/miniforge3/envs/fs_torch
